image: python:3.5.3

services:
  - rethinkdb:latest

test:
  only:
  - master
  script:
  - apt-get update -qy
  - apt-get install -y libxml2-dev libxslt1-dev lib32z1-dev libpython3-dev python3-dev python3-pip python3-setuptools libffi-dev
  - pyvenv env
  - source env/bin/activate
  - pip3 install -U setuptools pip
  - pip install -e .[dev]
  - bigchaindb --dev-allow-temp-keypair start &
  - sleep 5
  - python setup.py test
